---
# Configure Elasticsearch Node

#Create required directories
- name: Create Directories
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{pid_dir}}"
    - "{{log_dir}}"
    - "{{conf_dir}}"

- name: Create Data Directories
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{data_dirs}}"


#Copy the config template
- name: Copy Configuration File
  template: src=elasticsearch.yml.j2 dest={{conf_dir}}/elasticsearch.yml owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  register: config_updated
  notify: restart elasticsearch

#Copy the instance specific default file
- name: Copy Default File for Instance
  template: src=elasticsearch.j2 dest={{instance_default_file}} mode=0644 force=yes
  notify: restart elasticsearch

#Copy the logging.yml
- name: Copy log4j2.properties File for Instance
  template: src=log4j2.properties.j2 dest={{conf_dir}}/log4j2.properties owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch

- name: Copy jvm.options File for Instance
  template: src=jvm.options.j2 dest={{conf_dir}}/jvm.options owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch

- name: Include tasks specific to installed service manager
  include: elasticsearch-{{ ansible_service_mgr }}.yml
